// convpng v7.2
// this file contains all the graphics sources for easy inclusion in a project
#ifndef __logo_gfx__
#define __logo_gfx__
#include <stdint.h>

#define logo_gfx_transparent_color_index 0

#define brick_stairs_east_width 25
#define brick_stairs_east_height 27
#define brick_stairs_east_size 677
extern uint8_t brick_stairs_east_data[677];
#define brick_stairs_east ((gfx_sprite_t*)brick_stairs_east_data)
#define brick_stairs_west_width 25
#define brick_stairs_west_height 27
#define brick_stairs_west_size 677
extern uint8_t brick_stairs_west_data[677];
#define brick_stairs_west ((gfx_sprite_t*)brick_stairs_west_data)
#define brick_width 25
#define brick_height 27
#define brick_size 677
extern uint8_t brick_data[677];
#define brick ((gfx_sprite_t*)brick_data)
#define coal_ore_width 25
#define coal_ore_height 27
#define coal_ore_size 677
extern uint8_t coal_ore_data[677];
#define coal_ore ((gfx_sprite_t*)coal_ore_data)
#define dirt_width 25
#define dirt_height 27
#define dirt_size 677
extern uint8_t dirt_data[677];
#define dirt ((gfx_sprite_t*)dirt_data)
#define grass_block_width 25
#define grass_block_height 27
#define grass_block_size 677
extern uint8_t grass_block_data[677];
#define grass_block ((gfx_sprite_t*)grass_block_data)
#define stone_brick_stairs_east_width 25
#define stone_brick_stairs_east_height 27
#define stone_brick_stairs_east_size 677
extern uint8_t stone_brick_stairs_east_data[677];
#define stone_brick_stairs_east ((gfx_sprite_t*)stone_brick_stairs_east_data)
#define stone_brick_stairs_west_width 25
#define stone_brick_stairs_west_height 27
#define stone_brick_stairs_west_size 677
extern uint8_t stone_brick_stairs_west_data[677];
#define stone_brick_stairs_west ((gfx_sprite_t*)stone_brick_stairs_west_data)
#define stone_brick_width 25
#define stone_brick_height 27
#define stone_brick_size 677
extern uint8_t stone_brick_data[677];
#define stone_brick ((gfx_sprite_t*)stone_brick_data)
#define stone_width 25
#define stone_height 27
#define stone_size 677
extern uint8_t stone_data[677];
#define stone ((gfx_sprite_t*)stone_data)
#define glass_pane_east_width 25
#define glass_pane_east_height 27
#define glass_pane_east_size 677
extern uint8_t glass_pane_east_data[677];
#define glass_pane_east ((gfx_sprite_t*)glass_pane_east_data)
#define glass_pane_west_width 25
#define glass_pane_west_height 27
#define glass_pane_west_size 677
extern uint8_t glass_pane_west_data[677];
#define glass_pane_west ((gfx_sprite_t*)glass_pane_west_data)
#define glass_block_width 25
#define glass_block_height 27
#define glass_block_size 677
extern uint8_t glass_block_data[677];
#define glass_block ((gfx_sprite_t*)glass_block_data)
#define water_surface_width 25
#define water_surface_height 27
#define water_surface_size 677
extern uint8_t water_surface_data[677];
#define water_surface ((gfx_sprite_t*)water_surface_data)
#define water_full_width 25
#define water_full_height 27
#define water_full_size 677
extern uint8_t water_full_data[677];
#define water_full ((gfx_sprite_t*)water_full_data)
#define stone_brick_2_width 25
#define stone_brick_2_height 27
#define stone_brick_2_size 677
extern uint8_t stone_brick_2_data[677];
#define stone_brick_2 ((gfx_sprite_t*)stone_brick_2_data)
#define stone_brick_stairs_east_2_width 25
#define stone_brick_stairs_east_2_height 27
#define stone_brick_stairs_east_2_size 677
extern uint8_t stone_brick_stairs_east_2_data[677];
#define stone_brick_stairs_east_2 ((gfx_sprite_t*)stone_brick_stairs_east_2_data)
#define stone_brick_stairs_west_2_width 25
#define stone_brick_stairs_west_2_height 27
#define stone_brick_stairs_west_2_size 677
extern uint8_t stone_brick_stairs_west_2_data[677];
#define stone_brick_stairs_west_2 ((gfx_sprite_t*)stone_brick_stairs_west_2_data)
#define stone_stairs_east_width 25
#define stone_stairs_east_height 27
#define stone_stairs_east_size 677
extern uint8_t stone_stairs_east_data[677];
#define stone_stairs_east ((gfx_sprite_t*)stone_stairs_east_data)
#define stone_stairs_west_width 25
#define stone_stairs_west_height 27
#define stone_stairs_west_size 677
extern uint8_t stone_stairs_west_data[677];
#define stone_stairs_west ((gfx_sprite_t*)stone_stairs_west_data)
#define sizeof_logo_gfx_pal 182
extern uint16_t logo_gfx_pal[91];

#endif
